/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    stock?: number;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): value is Book {
    return true;
}

export function BookFromJSON(json: any): Book {
    return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'author': json['author'] == null ? undefined : json['author'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'image': json['image'] == null ? undefined : json['image'],
        'stock': json['stock'] == null ? undefined : json['stock'],
    };
}

export function BookToJSON(json: any): Book {
    return BookToJSONTyped(json, false);
}

export function BookToJSONTyped(value?: Book | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'author': value['author'],
        'description': value['description'],
        'price': value['price'],
        'image': value['image'],
        'stock': value['stock'],
    };
}

