/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBook200Response
 */
export interface DeleteBook200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteBook200Response
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the DeleteBook200Response interface.
 */
export function instanceOfDeleteBook200Response(value: object): value is DeleteBook200Response {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function DeleteBook200ResponseFromJSON(json: any): DeleteBook200Response {
    return DeleteBook200ResponseFromJSONTyped(json, false);
}

export function DeleteBook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function DeleteBook200ResponseToJSON(json: any): DeleteBook200Response {
    return DeleteBook200ResponseToJSONTyped(json, false);
}

export function DeleteBook200ResponseToJSONTyped(value?: DeleteBook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

