/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfilOrderRequestBooksFulfilledInner } from './FulfilOrderRequestBooksFulfilledInner';
import {
    FulfilOrderRequestBooksFulfilledInnerFromJSON,
    FulfilOrderRequestBooksFulfilledInnerFromJSONTyped,
    FulfilOrderRequestBooksFulfilledInnerToJSON,
    FulfilOrderRequestBooksFulfilledInnerToJSONTyped,
} from './FulfilOrderRequestBooksFulfilledInner';

/**
 * 
 * @export
 * @interface FulfilOrderRequest
 */
export interface FulfilOrderRequest {
    /**
     * 
     * @type {Array<FulfilOrderRequestBooksFulfilledInner>}
     * @memberof FulfilOrderRequest
     */
    booksFulfilled: Array<FulfilOrderRequestBooksFulfilledInner>;
}

/**
 * Check if a given object implements the FulfilOrderRequest interface.
 */
export function instanceOfFulfilOrderRequest(value: object): value is FulfilOrderRequest {
    if (!('booksFulfilled' in value) || value['booksFulfilled'] === undefined) return false;
    return true;
}

export function FulfilOrderRequestFromJSON(json: any): FulfilOrderRequest {
    return FulfilOrderRequestFromJSONTyped(json, false);
}

export function FulfilOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfilOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'booksFulfilled': ((json['booksFulfilled'] as Array<any>).map(FulfilOrderRequestBooksFulfilledInnerFromJSON)),
    };
}

export function FulfilOrderRequestToJSON(json: any): FulfilOrderRequest {
    return FulfilOrderRequestToJSONTyped(json, false);
}

export function FulfilOrderRequestToJSONTyped(value?: FulfilOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booksFulfilled': ((value['booksFulfilled'] as Array<any>).map(FulfilOrderRequestBooksFulfilledInnerToJSON)),
    };
}

