/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfilOrderRequestBooksFulfilledInner
 */
export interface FulfilOrderRequestBooksFulfilledInner {
    /**
     * 
     * @type {number}
     * @memberof FulfilOrderRequestBooksFulfilledInner
     */
    numberOfBooks: number;
    /**
     * 
     * @type {string}
     * @memberof FulfilOrderRequestBooksFulfilledInner
     */
    shelf: string;
    /**
     * 
     * @type {string}
     * @memberof FulfilOrderRequestBooksFulfilledInner
     */
    book: string;
}

/**
 * Check if a given object implements the FulfilOrderRequestBooksFulfilledInner interface.
 */
export function instanceOfFulfilOrderRequestBooksFulfilledInner(value: object): value is FulfilOrderRequestBooksFulfilledInner {
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    return true;
}

export function FulfilOrderRequestBooksFulfilledInnerFromJSON(json: any): FulfilOrderRequestBooksFulfilledInner {
    return FulfilOrderRequestBooksFulfilledInnerFromJSONTyped(json, false);
}

export function FulfilOrderRequestBooksFulfilledInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfilOrderRequestBooksFulfilledInner {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfBooks': json['numberOfBooks'],
        'shelf': json['shelf'],
        'book': json['book'],
    };
}

export function FulfilOrderRequestBooksFulfilledInnerToJSON(json: any): FulfilOrderRequestBooksFulfilledInner {
    return FulfilOrderRequestBooksFulfilledInnerToJSONTyped(json, false);
}

export function FulfilOrderRequestBooksFulfilledInnerToJSONTyped(value?: FulfilOrderRequestBooksFulfilledInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfBooks': value['numberOfBooks'],
        'shelf': value['shelf'],
        'book': value['book'],
    };
}

