/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderBooks200Response
 */
export interface OrderBooks200Response {
    /**
     * 
     * @type {string}
     * @memberof OrderBooks200Response
     */
    orderId: string;
}

/**
 * Check if a given object implements the OrderBooks200Response interface.
 */
export function instanceOfOrderBooks200Response(value: object): value is OrderBooks200Response {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function OrderBooks200ResponseFromJSON(json: any): OrderBooks200Response {
    return OrderBooks200ResponseFromJSONTyped(json, false);
}

export function OrderBooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
    };
}

export function OrderBooks200ResponseToJSON(json: any): OrderBooks200Response {
    return OrderBooks200ResponseToJSONTyped(json, false);
}

export function OrderBooks200ResponseToJSONTyped(value?: OrderBooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

