/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderSummary
 */
export interface OrderSummary {
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    orderId: string;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: number; }}
     * @memberof OrderSummary
     */
    books: { [key: string]: number; };
}

/**
 * Check if a given object implements the OrderSummary interface.
 */
export function instanceOfOrderSummary(value: object): value is OrderSummary {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function OrderSummaryFromJSON(json: any): OrderSummary {
    return OrderSummaryFromJSONTyped(json, false);
}

export function OrderSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'books': json['books'],
    };
}

export function OrderSummaryToJSON(json: any): OrderSummary {
    return OrderSummaryToJSONTyped(json, false);
}

export function OrderSummaryToJSONTyped(value?: OrderSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'books': value['books'],
    };
}

