/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBooksOnShelf200Response
 */
export interface PlaceBooksOnShelf200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PlaceBooksOnShelf200Response
     */
    ok: boolean;
}

/**
 * Check if a given object implements the PlaceBooksOnShelf200Response interface.
 */
export function instanceOfPlaceBooksOnShelf200Response(value: object): value is PlaceBooksOnShelf200Response {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function PlaceBooksOnShelf200ResponseFromJSON(json: any): PlaceBooksOnShelf200Response {
    return PlaceBooksOnShelf200ResponseFromJSONTyped(json, false);
}

export function PlaceBooksOnShelf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBooksOnShelf200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
    };
}

export function PlaceBooksOnShelf200ResponseToJSON(json: any): PlaceBooksOnShelf200Response {
    return PlaceBooksOnShelf200ResponseToJSONTyped(json, false);
}

export function PlaceBooksOnShelf200ResponseToJSONTyped(value?: PlaceBooksOnShelf200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

