/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBooksRequest
 */
export interface PlaceBooksRequest {
    /**
     * 
     * @type {number}
     * @memberof PlaceBooksRequest
     */
    numberOfBooks: number;
}

/**
 * Check if a given object implements the PlaceBooksRequest interface.
 */
export function instanceOfPlaceBooksRequest(value: object): value is PlaceBooksRequest {
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    return true;
}

export function PlaceBooksRequestFromJSON(json: any): PlaceBooksRequest {
    return PlaceBooksRequestFromJSONTyped(json, false);
}

export function PlaceBooksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBooksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfBooks': json['numberOfBooks'],
    };
}

export function PlaceBooksRequestToJSON(json: any): PlaceBooksRequest {
    return PlaceBooksRequestToJSONTyped(json, false);
}

export function PlaceBooksRequestToJSONTyped(value?: PlaceBooksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfBooks': value['numberOfBooks'],
    };
}

