/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrderRequest,
  FulfilOrderRequest,
  OrderBooks200Response,
  OrderSummary,
  PlaceBooksOnShelf200Response,
} from '../models/index';
import {
    CreateOrderRequestFromJSON,
    CreateOrderRequestToJSON,
    FulfilOrderRequestFromJSON,
    FulfilOrderRequestToJSON,
    OrderBooks200ResponseFromJSON,
    OrderBooks200ResponseToJSON,
    OrderSummaryFromJSON,
    OrderSummaryToJSON,
    PlaceBooksOnShelf200ResponseFromJSON,
    PlaceBooksOnShelf200ResponseToJSON,
} from '../models/index';

export interface FulfilOrderOperationRequest {
    orderId: string;
    fulfilOrderRequest: FulfilOrderRequest;
}

export interface OrderBooksRequest {
    createOrderRequest: CreateOrderRequest;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for fulfilOrder without sending the request
     */
    async fulfilOrderRequestOpts(requestParameters: FulfilOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling fulfilOrder().'
            );
        }

        if (requestParameters['fulfilOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'fulfilOrderRequest',
                'Required parameter "fulfilOrderRequest" was null or undefined when calling fulfilOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders/{orderId}/fulfil`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FulfilOrderRequestToJSON(requestParameters['fulfilOrderRequest']),
        };
    }

    /**
     * Fulfil an order
     */
    async fulfilOrderRaw(requestParameters: FulfilOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaceBooksOnShelf200Response>> {
        const requestOptions = await this.fulfilOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceBooksOnShelf200ResponseFromJSON(jsonValue));
    }

    /**
     * Fulfil an order
     */
    async fulfilOrder(requestParameters: FulfilOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaceBooksOnShelf200Response> {
        const response = await this.fulfilOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrders without sending the request
     */
    async listOrdersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List orders
     */
    async listOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderSummary>>> {
        const requestOptions = await this.listOrdersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderSummaryFromJSON));
    }

    /**
     * List orders
     */
    async listOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderSummary>> {
        const response = await this.listOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for orderBooks without sending the request
     */
    async orderBooksRequestOpts(requestParameters: OrderBooksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrderRequest',
                'Required parameter "createOrderRequest" was null or undefined when calling orderBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrderRequestToJSON(requestParameters['createOrderRequest']),
        };
    }

    /**
     * Create an order
     */
    async orderBooksRaw(requestParameters: OrderBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderBooks200Response>> {
        const requestOptions = await this.orderBooksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderBooks200ResponseFromJSON(jsonValue));
    }

    /**
     * Create an order
     */
    async orderBooks(requestParameters: OrderBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderBooks200Response> {
        const response = await this.orderBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
