/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlaceBooksOnShelf200Response,
  PlaceBooksRequest,
  ShelfStock,
} from '../models/index';
import {
    PlaceBooksOnShelf200ResponseFromJSON,
    PlaceBooksOnShelf200ResponseToJSON,
    PlaceBooksRequestFromJSON,
    PlaceBooksRequestToJSON,
    ShelfStockFromJSON,
    ShelfStockToJSON,
} from '../models/index';

export interface FindBookOnShelfRequest {
    bookId: string;
}

export interface PlaceBooksOnShelfRequest {
    shelf: string;
    bookId: string;
    placeBooksRequest: PlaceBooksRequest;
}

/**
 * 
 */
export class WarehouseApi extends runtime.BaseAPI {

    /**
     * Creates request options for findBookOnShelf without sending the request
     */
    async findBookOnShelfRequestOpts(requestParameters: FindBookOnShelfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookId'] == null) {
            throw new runtime.RequiredError(
                'bookId',
                'Required parameter "bookId" was null or undefined when calling findBookOnShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warehouse/books/{bookId}`;
        urlPath = urlPath.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters['bookId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async findBookOnShelfRaw(requestParameters: FindBookOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShelfStock>>> {
        const requestOptions = await this.findBookOnShelfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShelfStockFromJSON));
    }

    /**
     */
    async findBookOnShelf(requestParameters: FindBookOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShelfStock>> {
        const response = await this.findBookOnShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for placeBooksOnShelf without sending the request
     */
    async placeBooksOnShelfRequestOpts(requestParameters: PlaceBooksOnShelfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['shelf'] == null) {
            throw new runtime.RequiredError(
                'shelf',
                'Required parameter "shelf" was null or undefined when calling placeBooksOnShelf().'
            );
        }

        if (requestParameters['bookId'] == null) {
            throw new runtime.RequiredError(
                'bookId',
                'Required parameter "bookId" was null or undefined when calling placeBooksOnShelf().'
            );
        }

        if (requestParameters['placeBooksRequest'] == null) {
            throw new runtime.RequiredError(
                'placeBooksRequest',
                'Required parameter "placeBooksRequest" was null or undefined when calling placeBooksOnShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/warehouse/shelves/{shelf}/books/{bookId}`;
        urlPath = urlPath.replace(`{${"shelf"}}`, encodeURIComponent(String(requestParameters['shelf'])));
        urlPath = urlPath.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters['bookId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaceBooksRequestToJSON(requestParameters['placeBooksRequest']),
        };
    }

    /**
     */
    async placeBooksOnShelfRaw(requestParameters: PlaceBooksOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaceBooksOnShelf200Response>> {
        const requestOptions = await this.placeBooksOnShelfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceBooksOnShelf200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async placeBooksOnShelf(requestParameters: PlaceBooksOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaceBooksOnShelf200Response> {
        const response = await this.placeBooksOnShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
